// armory-react/src/components/Details.js
import React, { Component } from 'react'
import PropTypes from 'prop-types'
import { Link } from 'react-router-dom'

import * as products from '../fetcher/products'
import * as comments from '../fetcher/comments'

import Comments from '../components/Comments'

class Details extends Component {
  constructor(props) {
    super(props)

    this.state = {
      product: {},
      comments: [],
      user: JSON.parse(localStorage.getItem('user')),
      isAdded: false
    }
  }

  updateComment = comment => {
    comments.updateComment(comment).then()
  }

  deleteComment = commentId => {
    comments.deleteComment(commentId).then(() => {
      this.fetchComments(this.state.product._id)
    })
  }

  addComment = comment => {
    comments.createComment(comment).then((newComment) => {
      this.setState({ comments: [...this.state.comments, newComment] })
    })
  }

  addProductToFavorites = () => {
    let id = this.props.match.params.productId
    let user = this.state.user
    if (!this.state.isAdded) {
      this.props.createNotification('info', 'Added to favorites')
      user.favorites = [...user.favorites, id]
    } else {
      this.props.createNotification('info', 'Removed from favorites')
      user.favorites = user.favorites.filter(x => x !== id)
    }
    localStorage.setItem('user', JSON.stringify(user))
    this.setState({ isAdded: !this.state.isAdded, user })
    this.props.update(user)
  }

  formatAdditionalInformation(data) {
    let result = ''
    for (const key in data) {
      result += key + ': ' + data[key] + '<br />'
    }
    return result
  }

  fetchComments(id) {
    comments.getProductComments(id).then(comments => {
      this.setState({ comments })
    })
  }

  componentDidMount() {
    let id = this.props.match.params.productId
    products.getProductById(id).then(product => {
      this.setState({
        product
      })
    })
    this.fetchComments(id)
    if (this.state.user) {
      this.setState({
        isAdded: this.state.user.favorites
          .indexOf(this.props.match.params.productId) > -1
      })
    }
  }

  render() {
    let product = this.state.product
    let additionalInformation = ''
    if (product.additionalInformation && product.additionalInformation.length > 0) {
      additionalInformation = 'Additional information: ' + product.additionalInformation.join(', ')
    }
    let price = product.promo > 0 ?
      (+product.price - +product.price * (product.promo / 100)).toFixed(2)
      + ' (' + product.price + ')'
      : product.price
    let user = localStorage.getItem('user')
    let addToFavorites = user ? <button className='App-add-to-favorites-btn' onClick={this.addProductToFavorites}>{this.state.isAdded ? 'Remove from favorites' : 'Add to favorites'}</button> : ''
    let isAdmin = user && JSON.parse(localStorage.getItem('user')).roles[0] === 'Admin'
    let editProduct = isAdmin ? <button className='App-add-to-favorites-btn'><Link className='App-create-link' to={`/edit/${this.props.match.params.productId}`}>Edit product</Link></button> : ''
    return (
      <div>
        {product !== {}
          ? <div>
            <div className='App-body-title'>
              <p>{product.name} details</p>
              {addToFavorites}
              {editProduct}
            </div>
            <div className='App-details'>
              <p>{product.name}</p>
              <p>{price}</p>
              <p>{product.description}</p>
              {additionalInformation}
            </div>
            <div className='App-details-img-container'>
              <img className='App-details-img' src={this.state.product.img} alt={this.state.product.name} />
            </div>
          </div>
          : 'Loading...'}

        {this.state.user
          ? <Comments
            productId={this.state.product._id}
            comments={this.state.comments}
            author={this.state.user.username}
            addComment={this.addComment}
            deleteComment={this.deleteComment}
            updateComment={this.updateComment}
            createNotification={this.props.createNotification}
          />
          : ''}
      </div>
    )
  }
}

Details.propTypes = {
  update: PropTypes.func.isRequired,
  createNotification: PropTypes.func.isRequired
}

export default Details

// Angular/armory-angular/src/app/products/details/details.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { AuthService } from '../../services/auth.service';
import { ToastrService } from 'ngx-toastr';
import { ProductsService } from '../../services/products.service';
import { CommentsService } from '../../services/comments.service';

@Component({
  selector: 'app-details',
  templateUrl: './details.component.html',
  styleUrls: ['./details.component.css']
})
export class ProductDetailsComponent implements OnInit {

  private ADD_TEXT = 'Add to favorites';
  private REMOVE_TEXT = 'Remove from favorites';
  private POST_TEXT = 'Post comment';
  private NEW_TEXT = 'New comment';

  addPostCommentText: string = 'New comment';
  product: any;
  comments: any;
  showInput: boolean = false;
  comment: string = '';
  newComment: string;
  productId: string;
  removeComment: Function;
  addToFavoritesBtnText: string;

  //TODO FIX ADD TO FAVORITES BUTTON
  constructor(
    private productsService: ProductsService,
    private commentsService: CommentsService,
    private route: ActivatedRoute,
    private authService: AuthService,
    private toastr: ToastrService
  ) { }

  ngOnInit() {
    this.addToFavoritesBtnText = this.checkAddButtonText();
      this.route.params.subscribe(params => {
        this.productId = params['productId'];
        this.productsService.getProductDetailsById(this.productId).subscribe(data => {
          this.product = data;
        });
        this.productsService.getProductCommentsByProductId(this.productId)
          .subscribe(data => {
            this.comments = data;
          });
      })
    this.removeComment = this.remove.bind(this);
  }

  isLoggedIn() {
    return this.authService.isLoggedIn();
  }

  isAdmin() {
    return this.authService.isAdmin();
  }

  checkAddButtonText() {
    if (this.authService.getFavorites().includes(this.productId)) {
      console.log('in');
      return 'Remove from favorites';
    }
    return 'Add to favorites';
  }

  addPostComment() {
    if (this.addPostCommentText === this.POST_TEXT) {
      if (this.comment === '') {
        this.toastr.error('You cannot submit an empty comment');
        this.addPostCommentText === this.POST_TEXT ? this.addPostCommentText = this.NEW_TEXT : this.addPostCommentText = this.POST_TEXT;
        this.addPostCommentText === this.POST_TEXT ? this.showInput = true : this.showInput = false;
        return;
      }
      let comment = {
        text: this.comment,
        productId: this.productId,
        author: localStorage.getItem('username')
      }
      this.commentsService.createComment(comment).subscribe(comment => {
        this.comments.push(comment);
        this.toastr.success('Comment added');
      });
    }
    this.addPostCommentText === this.POST_TEXT ?
      this.addPostCommentText = this.NEW_TEXT :
      this.addPostCommentText = this.POST_TEXT;

    this.addPostCommentText === this.POST_TEXT ?
      this.showInput = true :
      this.showInput = false;

    this.comment = '';
  }

  remove(id) {
    this.comments = this.comments.filter(x => x._id !== id);
    this.commentsService.deleteComment(id).subscribe(data => {
      this.toastr.warning('Comment removed');
    });
  }

  addProductToFavorites() {
    let favorites = this.authService.getFavorites();
    let message = `Added ${this.product.name} to favorites`;
    if (this.addToFavoritesBtnText == this.ADD_TEXT) {
      favorites.push(this.productId);
      this.addToFavoritesBtnText = this.REMOVE_TEXT;
    } else {
      favorites = favorites.filter(x => x !== this.productId);
      this.addToFavoritesBtnText = this.ADD_TEXT
      message = `Removed ${this.product.name} from favorites`;
    }
    this.authService.setFavorites(favorites).subscribe(data => {
      this.toastr.info(message);
    });
  }

  additionalInformation(data) {
    if (data.length) {
      let result = '';
      for (const key in data) {
        if (+key % 2 === 1) {
          result += data[key] + '<br />';
        } else {
          result += '&#160;&#160;&#160;\u2022 ' + data[key] + ': ';
        }
      }
      return 'Additional information:<br />' + result.slice(0, -2).toLowerCase();
    }
    return '';
  }
}

<div *ngIf='product'>
  <div class='App-body-title'>
    <p>{{product.name}} details</p>
    <button class='App-add-to-favorites-btn' (click)=addProductToFavorites()>{{addToFavoritesBtnText}}</button>
    <button *ngIf='isAdmin()' class='App-add-to-favorites-btn'><a class='App-create-link' routerLink='/admin/edit/{{productId}}'>Edit product</a></button>
  </div>
  <div class='App-details'>
    <p>{{product.name}}</p>
    <p>{{price}}</p>
    <p>{{product.description}}</p>
    <p [innerHtml]='additionalInformation(product.additionalInformation)'></p>
  </div>
  <div class='App-details-img-container'>
    <img class='App-details-img' src={{product.img}} alt='{{product.name}}' />
  </div>
</div>
<div class='App-comments'>
  <div class='App-body-title-comments'>
    <p>Comments</p>
  </div>
  <div class='App-details-comments'>
    <div *ngFor='let comment of comments'>
      <app-comment [comment]='comment' [removeComment]='removeComment'></app-comment>
    </div>
    <div class='App-add-comment-btn'>
      <div *ngIf='showInput'>
        <input class='App-add-comment-input' type='text' [(ngModel)]="comment" />
      </div>
      <button class='App-add-comment' (click)='addPostComment()'>
        {{addPostCommentText}}
      </button>
    </div>
  </div>
</div>
