// ReactJS/armory-react/src/components/MyProfile.js
import React, { Component } from 'react'
import PropTypes from 'prop-types'

class MyProfile extends Component {
  constructor(props) {
    super(props)

    this.state = {
      isEditing: false,
      name: this.props.user.name,
      email: this.props.user.email,
      imgUrl: this.props.user.imgUrl
    }
  }

  editClick = () => {
    if (this.state.isEditing) {
      let user = JSON.parse(localStorage.getItem('user'))
      user.imgUrl = this.state.imgUrl
      user.name = this.state.name
      user.email = this.state.email
      let toReturn = this.validateUserData(user)
      if (toReturn)
        return
      localStorage.setItem('user', JSON.stringify(user))
      this.props.createNotification('info', 'Profile updated')
      this.props.update(user)
    }
    this.setState({ isEditing: !this.state.isEditing })
  }

  inputChange = (e, key) => {
    let state = this.state
    state[key] = e.target.value
    this.setState(state)
  }

  validateUserData(user) {
    if (user.name.length < 4) {
      this.props.createNotification('error', 'Name must be at least 3 symbols long')
      return true
    }
  }

  render() {
    return (
      <div>
        <div className='App-body-title'><p>MY PROFILE</p></div>
        <div className='App-details'>
          <p>{'Username: ' + this.props.user.username}</p>
          {this.state.isEditing ?
            <div>
              <p>
                <label>
                  Name: <input className='App-profile-form-input' type='text' value={this.state.name} onChange={(e) => this.inputChange(e, 'name')} required />
                </label>
              </p>
              <p>
                <label>
                  Email: <input className='App-profile-form-input' type='text' value={this.state.email} onChange={(e) => this.inputChange(e, 'email')} required />
                </label>
              </p>
              <p>
                <label>
                  Image url: <input className='App-profile-form-input' type='url' value={this.state.imgUrl} onChange={(e) => this.inputChange(e, 'imgUrl')} required />
                </label>
              </p>
            </div>
            :
            <div>
              <p>{'Name: ' + this.state.name}</p>
              <p>{'Email: ' + this.state.email}</p>
            </div>
          }
          <button className='App-profile-btn' onClick={this.editClick}>
            {this.state.isEditing ? 'Save' : 'Edit'}
          </button>
        </div>
        <div className='App-details-img-container'>
          <img className='App-details-img' src={this.state.imgUrl ||
            'http://www.personalbrandingblog.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640-300x300.png'} alt={'Profile'} />
        </div>
      </div>
    )
  }
}

MyProfile.propTypes = {
  user: PropTypes.object.isRequired,
  update: PropTypes.func.isRequired,
  createNotification: PropTypes.func.isRequired
}

export default MyProfile

// Angular/armory-angular/src/app/account/my-profile/my-profile.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Observable } from 'rxjs';

import { AuthService } from '../../services/auth.service';
import { ToastrService } from 'ngx-toastr';

@Component({
  selector: 'app-my-profile',
  templateUrl: './my-profile.component.html',
  styleUrls: ['./my-profile.component.css']
})
export class MyProfileComponent implements OnInit {

  myForm: FormGroup;
  isEditing: boolean;
  user: any;
  username: string;

  constructor(
    private authService: AuthService,
    private toastr: ToastrService,
    private fb: FormBuilder,
  ) {
    this.isEditing = false;
  }

  ngOnInit() {
    this.user = this.authService.isLoggedIn();
    this.username = this.user.username;
    this.myForm = this.fb.group({
      name: [this.user.name, [
        Validators.required,
        Validators.minLength(4),
        Validators.maxLength(16)
      ]],
      email: [this.user.email, [
        Validators.required,
        Validators.email
      ]],
      imgUrl: [this.user.imgUrl, []]
    });
  }

  editClick() {
    this.isEditing = true;
  }

  submit() {
    this.isEditing = false;
    this.user.email = this.email.value;
    this.user.name = this.name.value;
    this.user.imgUrl = this.imgUrl.value;
    this.authService.update(this.user).subscribe(user => {
      this.toastr.success('Profile updated');
    });
  }

  get name() {
    return this.myForm.get('name');
  }

  get email() {
    return this.myForm.get('email');
  }

  get imgUrl() {
    return this.myForm.get('imgUrl');
  }
}

<div>
  <div class='App-body-title'>
    <p>MY PROFILE</p>
  </div>
  <div class='App-details'>
    <p>Username: {{user.username}}</p>
    <div *ngIf='!isEditing'>
      <p>Name: {{name.value}}</p>
      <p>Email: {{email.value}}</p>
    </div>
    <button class='App-profile-btn' (click)='editClick()' *ngIf='!isEditing'>Edit</button>
    <form [formGroup]="myForm" (submit)='submit()' *ngIf='isEditing'>
      <p>
        <label>
          Name:
          <input class='App-profile-form-input' type='text' formControlName='name' required />
          <div class='App-input-error' *ngIf='name.errors?.required && name.touched'>Name is required</div>
          <div class='App-input-error' *ngIf='name.errors?.minlength && name.touched'>Name must be at least 4 symbols</div>
          <div class='App-input-error' *ngIf='name.errors?.maxlength && name.touched'>Name must be less than 16 symbols</div>
        </label>
      </p>
      <p>
        <label>
          Email:
          <input class='App-profile-form-input' type='email' formControlName='email' />
          <div class='App-input-error' *ngIf='email.errors?.required && email.touched'>Email is required</div>
          <div class='App-input-error' *ngIf='email.errors?.email && email.touched'>Provide a valid email</div>
        </label>
      </p>
      <p>
        <label>
          Image url:
          <input class='App-profile-form-input' type='url' formControlName='imgUrl' required />
          <div class='App-input-error' *ngIf='imgUrl.errors?.required && imgUrl.touched'>Image url is required</div>
        </label>
      </p>
      <button class='App-profile-btn' type='submit' [disabled]='myForm.invalid'>Save</button>
    </form>
  </div>
  <div class='App-details-img-container'>
    <img class='App-details-img' src='{{imgUrl.value}}' alt='Profile' />
  </div>
</div>
