// Angular/armory-angular/src/app/auth/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { AuthService } from '../auth.service';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent implements OnInit {

  myForm: FormGroup;

  constructor(
    private fb: FormBuilder,
    private authService: AuthService
  ) { }

  ngOnInit() {
    this.myForm = this.fb.group({
      name: ['', [
        Validators.required,
        Validators.minLength(4),
        Validators.maxLength(16)
      ]],
      username: ['', [
        Validators.required,
        Validators.minLength(4),
        Validators.maxLength(16)
      ]],
      email: ['', [
        Validators.required,
        Validators.email
      ]],
      password: ['', [
        Validators.required,
        Validators.minLength(6)
      ]],
      password2: ['', [
        Validators.required,
        Validators.minLength(6)
      ]]
    })
  }

  get name() {
    return this.myForm.get('name');
  }

  get username() {
    return this.myForm.get('username');
  }

  get email() {
    return this.myForm.get('email');
  }

  get password() {
    return this.myForm.get('password');
  }

  get password2() {
    return this.myForm.get('password2');
  }

  submit() {
    this.authService.register(this.myForm.value);
  }
}

<div class='App-body-title'>
  <p>REGISTER</p>
</div>
<form class='App-auth' [formGroup]='myForm' (submit)='submit()'>
  <p>
    <label>
      Name
      <input class='App-form-input' type='text' formControlName='name' />
      <div class='App-input-error' *ngIf='name.errors?.required && name.touched'>Name is required</div>
      <div class='App-input-error' *ngIf='name.errors?.minlength && name.touched'>Name must be at least 4 symbols</div>
      <div class='App-input-error' *ngIf='name.errors?.maxlength && name.touched'>Name must be less than 16 symbols</div>
    </label>
  </p>
  <p>
    <label>
      Username
      <input class='App-form-input' type='text' formControlName='username' />
      <div class='App-input-error' *ngIf='username.errors?.required && username.touched'>Username is required</div>
      <div class='App-input-error' *ngIf='username.errors?.minlength && username.touched'>Name must be at least 4 symbols</div>
      <div class='App-input-error' *ngIf='username.errors?.maxlength && username.touched'>Name must be less than 16 symbols</div>
    </label>
  </p>
  <p>
    <label>
      Email
      <input class='App-form-input' type='email' formControlName='email' />
      <div class='App-input-error' *ngIf='email.errors?.required && email.touched'>Email is required</div>
      <div class='App-input-error' *ngIf='email.errors?.email && email.touched'>Provide a valid email</div>
    </label>
  </p>
  <p>
    <label>
      Password
      <input class='App-form-input' type='password' formControlName='password' />
      <div class='App-input-error' *ngIf='password.errors?.required && password.touched'>Password is required</div>
      <div class='App-input-error' *ngIf='password.errors?.minlength && password.touched'>Password must be at least 6 symbols</div>
    </label>
  </p>
  <p>
    <label>
      Confirm Password
      <input class='App-form-input' type='password' formControlName='password2' />
      <div class='App-input-error' *ngIf='password2.errors?.required && password2.touched'>Confirm password is required</div>
      <div class='App-input-error' *ngIf='password2.errors?.minlength && password2.touched'>Confirm password must be at least 6 symbols</div>
      <div class='App-input-error' *ngIf='password2.valid && password.valid && password2.value !== password.value'>Passwords don't match</div>
    </label>
  </p>
  <input class='App-form-submit' type='submit' [disabled]='myForm.invalid' />
</form>

// armory-react/src/components/Register.js
import React, { Component } from 'react'
import PropTypes from 'prop-types'

class Register extends Component {
  constructor(props) {
    super(props)

    this.state = {
      username: '',
      password: '',
      name: '',
      password2: '',
      email: ''
    }
  }

  inputChange = (e, key) => {
    let state = this.state
    state[key] = e.target.value
    this.setState(state)
  }

  formSubmit = e => {
    e.preventDefault()
    let user = {
      username: this.state.username,
      password: this.state.password,
      name: this.state.name,
      email: this.state.email,
      password2: this.state.password2,
      imgUrl: this.state.imgUrl
    }
    let toReturn = this.validateUserData(user)
    if (toReturn)
      return
    this.props.register(user).then(res => {
      if (res.code) {
        this.props.createNotification('Error', 'Username already exists')
        return
      }
      this.props.createNotification('success', 'Registered')
      this.props.updateAppState()
      this.props.history.push('/')
    })
  }

  validateUserData(user) {
    if (user.name.length < 4) {
      this.props.createNotification('error', 'Name should be at least 4 symbols long')
      return true
    }
    if (user.username.length < 4) {
      this.props.createNotification('error', 'Username should be at least 4 symbols long')
      return true
    }
    if (user.password.length < 6) {
      this.props.createNotification('error', 'Password should be at least 6 symbols long')
      return true
    }
    if (user.password2.length !== user.password.length) {
      this.props.createNotification('error', "Passwords don't match")
      return true
    }
    return false
  }

  render() {
    return (
      <div>
        <div className='App-body-title'><p>REGISTER</p></div>
        <form className='App-auth' onSubmit={this.formSubmit}>
          <p>
            <label>
              Name<input className='App-form-input' type='text' id='name' name='name'
                value={this.state.name} onChange={(e) => this.inputChange(e, 'name')} required />
            </label>
          </p>
          <p>
            <label>
              Username<input className='App-form-input' type='text' id='username' name='username'
                value={this.state.username} onChange={(e) => this.inputChange(e, 'username')} required />
            </label>
          </p>
          <p>
            <label>
              Email<input className='App-form-input' type='email' id='email' name='email'
                value={this.state.email} onChange={(e) => this.inputChange(e, 'email')} required />
            </label>
          </p>
          <p>
            <label>
              Password<input className='App-form-input' type='password' id='password' name='password'
                value={this.state.password} onChange={(e) => this.inputChange(e, 'password')} required />
            </label>
          </p>
          <p>
            <label>
              Confirm Password<input className='App-form-input' type='password' id='password2' name='password2'
                value={this.state.password2} onChange={(e) => this.inputChange(e, 'password2')} required />
            </label>
          </p>
          <input className='App-form-submit' type='submit' />
        </form>
      </div>
    )
  }
}

Register.propType = {
  register: PropTypes.func.isRequired,
  createNotification: PropTypes.func.isRequired,
  updateAppState: PropTypes.func.isRequired
}

export default Register
