// Angular/armory-angular/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { HomeService } from './home.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  newProducts$;
  promoProducts$;

  constructor(
    private homeService: HomeService
  ) { }

  ngOnInit() {
    this.newProducts$ = this.homeService.getNewProducts();
    this.promoProducts$ = this.homeService.getPromoProducts();
  }
}

<div>
  <div class='App-body-title'>
    <p>NEW</p>
  </div>
  <a *ngFor="let product of newProducts$ | async" class='App-product' routerLink='/products/details/{{product.id}}'>
    <p>{{product.name}}</p>
    <img class='App-img-product' src='{{product.img}}' alt='proelia' />
  </a>
  <div class='App-body-title'>
    <p>PROMO</p>
  </div>
  <a *ngFor="let product of promoProducts$ | async" class='App-product' routerLink='/products/details/{{product.id}}'>
    <p>{{product.name}}</p>
    <img class='App-img-product' src='{{product.img}}' alt='proelia' />
  </a>
</div>

// ReactJS/armory-react/src/components/Home.js
import React, { Component } from 'react'
import Products from './Products'

import * as products from '../fetcher/products'

class Home extends Component {
  constructor (props) {
    super(props)

    this.state = {
      promoProducts: [],
      newProducts: []
    }
  }

  componentDidMount () {
    products.getPromoProducts().then(promoProducts => {
      this.setState({ promoProducts })
    })
    products.getNewProducts().then(newProducts => {
      this.setState({ newProducts })
    })
  }

  render () {
    return (
      <div>
        <div className='App-body-title'><p>{'NEW'}</p></div>
        <Products
          products={this.state.newProducts}
        />
        <div className='App-body-title'><p>{'PROMO'}</p></div>
        <Products
          products={this.state.promoProducts.slice(0, 3)}
        />
      </div>
    )
  }
}

export default Home
